// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBar: typeof import('./../components/chart/base-bar.vue')['default']
    BaseChart: typeof import('./../components/chart/base-chart.vue')['default']
    BaseLine: typeof import('./../components/chart/base-line.vue')['default']
    BasePie: typeof import('./../components/chart/base-pie.vue')['default']
    ChartPanel: typeof import('./../components/chart-panel/chart-panel.vue')['default']
    ConbineDialog: typeof import('./../components/combine-dialog/conbine-dialog.vue')['default']
    ConbineTrigger: typeof import('./../components/combine-dialog/conbine-trigger.tsx')['default']
    FormBuilder: typeof import('./../components/form/form-builder.tsx')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    NumberCount: typeof import('./../components/number-count/number-count.vue')['default']
    Pie: typeof import('./../components/chart/pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackHorizontal: typeof import('./../components/chart/stack-horizontal.vue')['default']
    SurveyPanel: typeof import('./../components/survey-panel/survey-panel.vue')['default']
    WaterFall: typeof import('./../components/chart/water-fall.vue')['default']
  }
}
